name: fort_monitor
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  auto_route: ^10.1.0+1
  flutter_svg: ^2.2.0
  mask_text_input_formatter: ^2.9.0
  file_picker: ^10.3.1
  google_fonts: ^6.1.0
  supabase_flutter: ^2.3.4
  flutter_secure_storage: ^9.0.0
  flutter_riverpod: ^2.5.1
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  auto_route_generator: ^10.2.3
  build_runner: ^2.5.4

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
